# compose.prod.yaml
version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword
      MYSQL_DATABASE: ticker_cy
      MYSQL_USER: admin
      MYSQL_PASSWORD: P@ssword
    volumes:
      - ticket_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pP@ssword"]
      timeout: 20s
      retries: 3
    networks:
      - mynetwork
    restart: always

  nextjs:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
      DATABASE_USER: admin
      DATABASE_PASSWORD: P@ssword
      DATABASE_NAME: ticker_cy
    depends_on:
      - db
    networks:
      - mynetwork
    command: ["npm", "run", "start"]
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  ticket_db: {}